test_script: &test_script |
    apt update && apt install --yes curl build-essential git
    /bin/sh -c 'curl -fsSL https://gist.githubusercontent.com/YOU54F/2e47eb0b653b6810dd6a0be9fc6820ea/raw/install.sh' | sh -s -- --ci -v 2.6.10
    echo 'export PATH=/root/.travelling-ruby/bin:${PATH}' >> /root/.profile
    source /root/.profile
    ruby --version
    which ruby
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /root/.profile
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/you54f/install/HEAD/install.sh)" || true
    source /root/.profile
    /home/linuxbrew/.linuxbrew/bin/brew --version

cli_amd_task:
  container:
    image: ubuntu:22.04
  test_script: *test_script

cli_arm_task:
  arm_container:
      image: ubuntu:22.04
  test_script: *test_script
